### ISSUE TITLE
include lastseen items to atom feed

### ISSUE THREAD

**Issue by osmtools** [mueschel/OsmLatestKeys#1]
could we test the following: remove `lastseen eq ""` from this line
https://github.com/mueschel/OsmLatestKeys/blob/430e4b793b8f147426cb5ece76b08a012e3e08b9/keylist.pl#L132
if `lastseen` then `updated` should be the lastseen-date
https://github.com/mueschel/OsmLatestKeys/blob/430e4b793b8f147426cb5ece76b08a012e3e08b9/keylist.pl#L136
if `lastseen` add `last seen on` after
https://github.com/mueschel/OsmLatestKeys/blob/430e4b793b8f147426cb5ece76b08a012e3e08b9/keylist.pl#L141

i think my feedly should notice this and update the items, and this modifications shouldn't break other feed readers .. i hope ;-)

Regards, Harald

**Comment by osmtools** [comment]
and of course remove `$num != 0` in the first `if`, or have lastseen items still a num>0 ?!

**Comment by osmtools** [comment]
and the firstseen-date should be `<published/>` as of https://tools.ietf.org/html/rfc4287#section-1.1 (example on page 3) and https://tools.ietf.org/html/rfc4287#section-4.2.9

**Comment by mueschel** [comment]
I added these changes.
